Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 2
    v.name = "Elastic Docker"
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    yum -y update
    yum install -y git nmap-netcat vim
    cd /home/vagrant
    git clone https://github.com/dennismartis/docker
  SHELL

  config.vm.provision :"docker"
  config.vm.provision :docker_compose, yml: "/home/vagrant/docker/websphere/docker-compose.yml", run: "always"

end