Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "jenkins-master"
  config.vm.network "private_network", ip: "192.168.10.100"
  config.vm.network :forwarded_port, guest: 8080, host: "8080"
  config.vm.provider "virtualbox" do |v|
    v.name = "jenkins-master"
  end
  config.hostsupdater.aliases = ["jenkins.localdomain.com"]
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
      sudo yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      subscription-manager repos --enable "rhel-*-optional-rpms" --enable "rhel-*-extras-rpms"  --enable "rhel-ha-for-rhel-*-server-rpms"
      sudo yum -y update
      sudo yum -y install wget
      sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins.io/redhat-stable/jenkins.repo
      sudo rpm --import http://pkg.jenkins.io/redhat-stable/jenkins.io.key
      sudo yum -y install jenkins java-1.8.0-openjdk
      sudo systemctl start jenkins
      sudo systemctl enable jenkins
      sleep 30
      while [ ! -f /var/lib/jenkins/secrets/initialAdminPassword ]
      do
        sleep 2
      done
      sudo cat /var/lib/jenkins/secrets/initialAdminPassword
      printf "Jenkins Console: http://jenkins.localdomain.com:8080 "
    SHELL
  end
end
